services:
  regression:
    image: mcr.microsoft.com/playwright:focal
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tests:/app/tests 
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    working_dir: /app
    command: /bin/sh -c "npx playwright test --reporter=allure-playwright --output=/app/allure-results"
