services:
  regression:
    image: mcr.microsoft.com/playwright:v1.50.0-noble
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./package.json:/app/package.json
    working_dir: /app
    command: /bin/sh -c "ls -la && npm install && npx playwright test"
