name: UI Tests

on: [push]

jobs:
  ui-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run UI-tests via docker-compose
        run: docker compose run regression /bin/sh -c "ls -la npm install && npx playwright test"
      - name: Save Allure Results
        if: always()
        run: |
          mkdir -p allure-results
          docker cp $(docker ps -qf "name=regression"):/app/allure-results ./allure-results
        shell: bash
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results

  build-test-report:
    needs: ui-tests
    runs-on: ubuntu-22.04
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results

      - name: Build Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

  deploy-to-github-pages:
    needs: build-test-report
    runs-on: ubuntu-22.04
    if: always()
    steps:
      - name: Deploy-to-GitHub-Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./allure-history
