name: UI tests

on: [push]

jobs:
  ui-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run UI-tests via docker-compose
        run: docker compose run regression /bin/sh -c "ls -la && npm install && npx playwright test"

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        continue-on-error: true
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
